development:
  adapter: postgresql
  encoding: unicode
  database: rails_checkout_transparente_development
  pool: 5
  username: pedro-shd
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails_checkout_transparente_test
  pool: 5
  username: pedro-shd
  password:
